---
- name: Check if system is debian
  fail:
    msg: 'This role supports debian only'
  when: ansible_os_family != 'Debian'

- name: Install packages
  apt:
    name: "{{ git_packages }}"
    state: present
    update_cache: yes

- name: Install Git LFS (buster/sid)
  apt:
    name: git-lfs
    state: present
  when: install_git_lfs and ansible_distribution_major_version == "buster/sid"

#TODO
- name: Install Git LFS (not buster/sid)
  debug:
    msg: "Currently only supported for buster/sid"
  when: install_git_lfs and ansible_distribution_major_version != "buster/sid"

- name: Configure global user settings
  become: no
  ini_file:
    section: user
    path: ~/.gitconfig
    state: present
    no_extra_spaces: no
    value: "{{ item.value }}"
    option: "{{ item.key }}"
    create: yes  # whether to create the config file if it's missing
  vars:
    git_user:
      email: "{{ git_user_email }}"
      name: "{{ git_user_name }}"
  with_dict: "{{ git_user }}"

# TODO other config

# TODO aliases

# TODO if git-lfs installed then init
