---
- name: Stop if os release is incompatible
  fail:
    msg: "{{ ansible_os_family }} is incompatible with this role. See README for details."
  when: ansible_os_family != 'Debian' and ansible_os_family != 'Ubuntu'

- name: Install packages
  become: yes
  apt:
    name: "{{ git_packages }}"
    state: present
    update_cache: yes

- name: Configure global user settings
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    group: "{{ ansible_user_id }}"
    owner: "{{ ansible_user_id }}"
    mode: "u=rw,g=r,o=r"

- import_tasks: lfs.yml
  tags: git-lfs
  when: git_lfs_install | bool

- import_tasks: prompt.yml
  tags: git-prompt
  when: git_prompt_install | bool
